figure('Name', 'Red energy loss');
plot(red.move_at_Z.set_speed_50.energy_loss);
grid on;
hold on;
plot(red.move_at_Z.set_speed_100.energy_loss);
plot(red.move_at_Z.set_speed_150.energy_loss);
% plot(red.move_at_XY.set_speed_400.energy_loss);
% plot(red.move_at_XY.set_speed_500.energy_loss);
ylim([-100, 10]);
figure('Name', 'Red torque');
plot(red.move_at_Z.set_speed_50.motors(1).torque);
grid on;
hold on;
plot(red.move_at_Z.set_speed_100.motors(1).torque);
plot(red.move_at_Z.set_speed_150.motors(1).torque);
% plot(red.move_at_XY.set_speed_400.motors(1).torque);
% plot(red.move_at_XY.set_speed_500.motors(1).torque);
ylim([-0.2, 0.4]);

figure('Name', 'Blue energy loss');
plot(blue.move_at_Z.set_speed_50.energy_loss);
grid on;
hold on;
plot(blue.move_at_Z.set_speed_100.energy_loss);
plot(blue.move_at_Z.set_speed_150.energy_loss);
% plot(blue.move_at_XY.set_speed_400.energy_loss);
% plot(blue.move_at_XY.set_speed_500.energy_loss);
ylim([-100, 10]);
figure('Name', 'Blue torque');
plot(blue.move_at_Z.set_speed_50.motors(1).torque);
grid on;
hold on;
plot(blue.move_at_Z.set_speed_100.motors(1).torque);
plot(blue.move_at_Z.set_speed_150.motors(1).torque);
% plot(blue.move_at_XY.set_speed_400.motors(1).torque);
% plot(blue.move_at_XY.set_speed_500.motors(1).torque);
ylim([-0.2, 0.4]);

figure('Name', 'Gray energy loss');
plot(gray.move_at_Z.set_speed_50.energy_loss);
grid on;
hold on;
plot(gray.move_at_Z.set_speed_100.energy_loss);
plot(gray.move_at_Z.set_speed_150.energy_loss);
% plot(gray.move_at_Z.set_speed_400.energy_loss);
% plot(gray.move_at_Z.set_speed_500.energy_loss);
ylim([-100, 10]);
figure('Name', 'Gray torque');
plot(gray.move_at_Z.set_speed_50.motors(1).torque);
grid on;
hold on;
plot(gray.move_at_Z.set_speed_100.motors(1).torque);
plot(gray.move_at_Z.set_speed_150.motors(1).torque);
% plot(gray.move_at_Z.set_speed_400.motors(1).torque);
% plot(gray.move_at_Z.set_speed_500.motors(1).torque);
ylim([-0.2, 0.4]);