sim_end_time = 5;
set_param('Mining_data/Set speed X', 'Value', num2str(0));
set_param('Mining_data/Set speed Y', 'Value', num2str(0));
set_param('Mining_data/Set angular speed', 'Value', num2str(-150));
sim_out = sim('Mining_data', 'StopTime', num2str(sim_end_time));
motors(1).reference = sim_out.get('motor1_reference');
motors(2).reference = sim_out.get('motor2_reference');
motors(3).reference = sim_out.get('motor3_reference');
motors(1).speed = sim_out.get('motor1_speed');
motors(2).speed = sim_out.get('motor2_speed');
motors(3).speed = sim_out.get('motor3_speed');
motors(1).current = sim_out.get('motor1_current');
motors(2).current = sim_out.get('motor2_current');
motors(3).current = sim_out.get('motor3_current');
sim_out = sim('energy_model', 'StopTime', num2str(sim_end_time));
motors(1).power = sim_out.get('power1');
motors(2).power = sim_out.get('power2');
motors(3).power = sim_out.get('power3');
motors(1).torque = sim_out.get('torque1');
motors(2).torque = sim_out.get('torque2');
motors(3).torque = sim_out.get('torque3');
kinetic_energy = sim_out.get('kinetic_energy');
energy_loss = sim_out.get('energy_loss');
red.move_at_Z.set_speed_150.motors = motors;
red.move_at_Z.set_speed_150.kinetic_energy = kinetic_energy;
red.move_at_Z.set_speed_150.energy_loss = energy_loss;